app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.tofact.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.tofact.com
                description: Chat client
                icon: element.svg
            - Jellyfin:
                href: https://jellyfin.tofact.com
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
            - Jellyseerr:
                href: https://jellyseerr.tofact.com
                description: Request media
                icon: jellyseerr.svg
            - Paperless:
                href: https://paperless.tofact.com
                description: Document management system
                icon: paperless.svg
          - Management:
            - Transmission:
                href: https://transmission.tofact.com
                description: Bittorrent client
                icon: transmission.svg
            - Prowlarr:
                href: https://prowlarr.tofact.com
                description: Indexer manager
                icon: prowlarr.svg
            - Radarr:
                href: https://radarr.tofact.com
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.tofact.com
                description: TV show manager
                icon: sonarr.svg
            - Kanidm:
                href: https://auth.tofact.com
                description: Identity management
                icon: https://auth.tofact.com/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.tofact.com
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.tofact.com
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.tofact.com
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://registry.tofact.com
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.tofact.com
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.tofact.com
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.tofact.com
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.tofact.com
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/khuedoan/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Router:
              - href: https://192.168.1.1
                icon: router.svg
            - Proxmox:
              - href: https://proxmox:8006
                icon: proxmox.svg
            - Google Cloud:
              - href: https://console.cloud.google.com
                icon: google-cloud-platform.svg
            - Oracle Cloud:
              - href: https://cloud.oracle.com
                icon: oracle-cloud.svg
