all:
  vars:
    control_plane_endpoint: 192.168.31.20
    load_balancer_ip_pool:
      - 192.168.31.224/27
metal:
  children:
    masters:
      hosts:
        metal2: {ansible_host: 192.168.31.22, mac: 'bc:24:11:ea:f6:ec', disk: sda, network_interface: ens18}
        metal3: {ansible_host: 192.168.31.23, mac: 'bc:24:11:dd:a5:26', disk: sda, network_interface: ens18}
        metal4: {ansible_host: 192.168.31.24, mac: 'bc:24:11:c3:f4:73', disk: sda, network_interface: ens18}
    workers:
      hosts:
        metal5: {ansible_host: 192.168.31.25, mac: 'bc:24:11:33:85:e2', disk: sda, network_interface: ens18}
